language: node_js
node_js: '8'

git:
  depth: 3

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    - NODE_ENV=test

before_script:
  - yarn mock-api &

script: yarn test
# after_success: yarn coverage
